---
title: tliyun's blog
email: 313766963@qq.com
author: tliyun
author_github: tliyun
description: |
  没有比人更高的山，没有比脚更长的路！
baseurl: "/"
url: http://tliyun.github.io/
paginate: 12
github:
  user: hugocarreira
  repository: jekyll-materializecss
  url: 
  status: true
home_bgfile: bg.jpg
sass:
  sass_dir: assets/css
  style: compressed
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
gems:
- jekyll-paginate
exclude:
- vendor
